// services/engine/src/invoices/pdf-generator.ts
//
// Invoice PDF generation using PDFKit.
// Generates professional invoices with RailSwitch branding.

import PDFDocument from 'pdfkit';
import type { Response } from 'express';

export interface InvoicePDFData {
  id: string;
  amount: number;
  currency: string;
  status: string;
  due_date: string;
  paid_at?: string;
  customer: {
    name: string;
    email: string;
  };
  plan: {
    name: string;
    amount: number;
  };
  merchant: {
    name: string;
  };
}

export function generateInvoicePDF(invoice: InvoicePDFData, res: Response) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=invoice-${invoice.id}.pdf`);
  doc.pipe(res);

  // Header
  doc.fontSize(24).fillColor('#6366f1').text('RailSwitch', { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666').text('Subscription Billing Engine');
  doc.moveDown(2);

  // Invoice title
  doc.fontSize(20).fillColor('#111').text('INVOICE', { align: 'right' });
  doc.fontSize(10).fillColor('#666');
  doc.text(`Invoice #: ${invoice.id}`, { align: 'right' });
  doc.text(`Date: ${new Date(invoice.due_date).toLocaleDateString()}`, { align: 'right' });
  doc.text(`Status: ${invoice.status.toUpperCase()}`, { align: 'right' });
  doc.moveDown(2);

  // From / To
  const leftX = 50;
  const rightX = 350;
  doc.fontSize(10).fillColor('#999').text('FROM', leftX, doc.y);
  doc.fillColor('#111').text(invoice.merchant.name || 'RailSwitch Merchant', leftX, doc.y + 5);
  doc.moveDown(1.5);
  doc.fillColor('#999').text('BILL TO', leftX, doc.y);
  doc.fillColor('#111').text(invoice.customer.name, leftX, doc.y + 5);
  doc.text(invoice.customer.email, leftX, doc.y + 12);
  doc.moveDown(2);

  // Line items
  const tableTop = doc.y;
  doc.fillColor('#f5f5f5').rect(50, tableTop, 500, 25).fill();
  doc.fillColor('#333').fontSize(10).text('Description', 60, tableTop + 7);
  doc.text('Amount', 400, tableTop + 7, { width: 100, align: 'right' });
  doc.moveDown(1);

  doc.fillColor('#111').text(`${invoice.plan.name} Subscription`, 60, doc.y + 5);
  doc.text(`${invoice.currency} ${(invoice.amount / 100).toLocaleString()}`, 400, doc.y - 8, { width: 100, align: 'right' });
  doc.moveDown(1.5);

  // Total
  const totalY = doc.y + 10;
  doc.fillColor('#f5f5f5').rect(50, totalY, 500, 30).fill();
  doc.fillColor('#111').fontSize(12).font('Helvetica-Bold').text('Total', 60, totalY + 8);
  doc.text(`${invoice.currency} ${(invoice.amount / 100).toLocaleString()}`, 400, totalY + 8, { width: 100, align: 'right' });
  doc.font('Helvetica');
  doc.moveDown(3);

  // Payment info
  if (invoice.status === 'paid' && invoice.paid_at) {
    doc.fontSize(10).fillColor('#22c55e').text(`Paid on ${new Date(invoice.paid_at).toLocaleDateString()}`, { align: 'center' });
  } else if (invoice.status === 'uncollectible') {
    doc.fontSize(10).fillColor('#ef4444').text('Payment overdue — subscription may be cancelled', { align: 'center' });
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999').text('Generated by RailSwitch — railswitch.io', { align: 'center' });

  doc.end();
}
